server:
  port: 8083
spring:
  data:
    mongodb:
      database: 'courses-manager'
  security:
    filter:
      order: 10

insertTestData: true

spring.security.ignored: /**
spring.security.basic.enabled: false
spring.management.security.enabled: false