spring:
  security:
    filter:
      order: 10
server:
  port: 8081

springdoc:
  packagesToScan: md.ilie.coursesmanager.gateway.controller

graphql:
  playground:
    headers:
      Authorization: Bearer token